version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

workflows:
  build-test:
    jobs:
      - node/run:
            npm-run: build
            filters:
              branches:
                only:
                  - circle_Ci
      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - circle_Ci

      - heroku/deploy-via-git:
          requires:
            - node/run
            - node/test
          app-name: "joke-app-2"
          filters:
            branches:
              only:
                - circle_Ci

      - docker/publish:
          image: wendyafrim/joke-app:latest
          docker-username: wendyafrim
          docker-password: DOCKER_PASSWORD
          requires:
            - node/run
            - node/test
          filters:
            branches:
              only:
                - circle_Ci