version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

workflows:
  build-test:
    jobs:
      - node/run:
            npm-run: build
            filters:
              branches:
                only:
                  - circle_Ci
      - node/test:
          requires:
            - "node/run"
          filters:
            branches:
              only:
                - circle_Ci

      - heroku/deploy-via-git:
          requires:
            - node/run
            - node/test
          app-name: "joke-app-2"
          filters:
            branches:
              only:
                - circle_Ci

      - build-and-push:
        executor: docker/docker
        steps:
          - setup_remote_docker
          - checkout
          - docker/check
          - docker/build:
              image: wendyafrim/orb-test
          - docker/push:
              digest-path: /tmp/digest.txt
              image: wendyafrim/orb-test
          - run:
              command: |
                echo "Digest is: $(</tmp/digest.txt)"